build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    PYTHONUNBUFFERED: 1

    matrix:
        # Build for Visual Studio 2017
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
        # Build for Visual Studio 2015
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_ARCHS: x86_64
        # Build for Visual Studio 2012
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
          CONAN_VISUAL_VERSIONS: 12
          CONAN_ARCHS: x86_64
        # A x86 build
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_sword_and_sorcery
  - conan user # It creates the conan data directory

test_script:
  - run_ci conanfile.py
